version: '3.9'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "filterdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./initial_sql_script.sql:/docker-entrypoint-initdb.d/initial_sql_script.sql
    ports:
      - 5432:5432
